version: '3'
services:
    app:
        restart: always
        build: .
        image: pastbook:latest
        container_name: pastbook
        ports:
            - "80:80"
        networks:
            - pastBookNetwork
        links:
            - mysql
        volumes:
            - .:/var/www/html
    mysql:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - 'pastBookMySql:/var/lib/mysql'
        ports:
            - "3306:3306"
        networks:
            - pastBookNetwork
networks:
    pastBookNetwork:
        driver: bridge
volumes:
    pastBookMySql:
        driver: local
